# Generated by Django 5.0.9 on 2024-10-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_workflow_stage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubricinfo',
            options={'managed': True},
        ),
    ]
