# Generated by Django 5.0.9 on 2024-11-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_rubricinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubricinfo',
            options={'managed': False},
        ),
    ]
