

export const elementsData = [
  { number: 1, symbol: 'H', name: 'Hydrogen', weight: '1.008', column: 1, row: 1, category: 'nonmetal' },
  { number: 2, symbol: 'He', name: 'Helium', weight: '4.0026', column: 18, row: 1, category: 'noble gas' },
  { number: 3, symbol: 'Li', name: 'Lithium', weight: '6.94', column: 1, row: 2, category: 'alkali metal' },
  { number: 4, symbol: 'Be', name: 'Beryllium', weight: '9.0122', column: 2, row: 2, category: 'alkaline earth metal' },
  { number: 5, symbol: 'B', name: 'Boron', weight: '10.81', column: 13, row: 2, category: 'metalloid' },
  { number: 6, symbol: 'C', name: 'Carbon', weight: '12.011', column: 14, row: 2, category: 'nonmetal' },
  { number: 7, symbol: 'N', name: 'Nitrogen', weight: '14.007', column: 15, row: 2, category: 'nonmetal' },
  { number: 8, symbol: 'O', name: 'Oxygen', weight: '15.999', column: 16, row: 2, category: 'nonmetal' },
  { number: 9, symbol: 'F', name: 'Fluorine', weight: '18.998', column: 17, row: 2, category: 'halogen' },
  { number: 10, symbol: 'Ne', name: 'Neon', weight: '20.180', column: 18, row: 2, category: 'noble gas' },
  { number: 11, symbol: 'Na', name: 'Sodium', weight: '22.990', column: 1, row: 3, category: 'alkali metal' },
  { number: 12, symbol: 'Mg', name: 'Magnesium', weight: '24.305', column: 2, row: 3, category: 'alkaline earth metal' },
  { number: 13, symbol: 'Al', name: 'Aluminum', weight: '26.982', column: 13, row: 3, category: 'post-transition metal' },
  { number: 14, symbol: 'Si', name: 'Silicon', weight: '28.085', column: 14, row: 3, category: 'metalloid' },
  { number: 15, symbol: 'P', name: 'Phosphorus', weight: '30.974', column: 15, row: 3, category: 'nonmetal' },
  { number: 16, symbol: 'S', name: 'Sulfur', weight: '32.06', column: 16, row: 3, category: 'nonmetal' },
  { number: 17, symbol: 'Cl', name: 'Chlorine', weight: '35.45', column: 17, row: 3, category: 'halogen' },
  { number: 18, symbol: 'Ar', name: 'Argon', weight: '39.948', column: 18, row: 3, category: 'noble gas' },
  { number: 19, symbol: 'K', name: 'Potassium', weight: '39.098', column: 1, row: 4, category: 'alkali metal' },
  { number: 20, symbol: 'Ca', name: 'Calcium', weight: '40.078', column: 2, row: 4, category: 'alkaline earth metal' },
  { number: 21, symbol: 'Sc', name: 'Scandium', weight: '44.956', column: 3, row: 4, category: 'transition metal' },
  { number: 22, symbol: 'Ti', name: 'Titanium', weight: '47.867', column: 4, row: 4, category: 'transition metal' },
  { number: 23, symbol: 'V', name: 'Vanadium', weight: '50.942', column: 5, row: 4, category: 'transition metal' },
  { number: 24, symbol: 'Cr', name: 'Chromium', weight: '51.996', column: 6, row: 4, category: 'transition metal' },
  { number: 25, symbol: 'Mn', name: 'Manganese', weight: '54.938', column: 7, row: 4, category: 'transition metal' },
  { number: 26, symbol: 'Fe', name: 'Iron', weight: '55.845', column: 8, row: 4, category: 'transition metal' },
  { number: 27, symbol: 'Co', name: 'Cobalt', weight: '58.933', column: 9, row: 4, category: 'transition metal' },
  { number: 28, symbol: 'Ni', name: 'Nickel', weight: '58.693', column: 10, row: 4, category: 'transition metal' },
  { number: 29, symbol: 'Cu', name: 'Copper', weight: '63.546', column: 11, row: 4, category: 'transition metal' },
  { number: 30, symbol: 'Zn', name: 'Zinc', weight: '65.38', column: 12, row: 4, category: 'transition metal' },
  { number: 31, symbol: 'Ga', name: 'Gallium', weight: '69.723', column: 13, row: 4, category: 'post-transition metal' },
  { number: 32, symbol: 'Ge', name: 'Germanium', weight: '72.63', column: 14, row: 4, category: 'metalloid' },
  { number: 33, symbol: 'As', name: 'Arsenic', weight: '74.922', column: 15, row: 4, category: 'metalloid' },
  { number: 34, symbol: 'Se', name: 'Selenium', weight: '78.971', column: 16, row: 4, category: 'nonmetal' },
  { number: 35, symbol: 'Br', name: 'Bromine', weight: '79.904', column: 17, row: 4, category: 'halogen' },
  { number: 36, symbol: 'Kr', name: 'Krypton', weight: '83.798', column: 18, row: 4, category: 'noble gas' },
  { number: 37, symbol: 'Rb', name: 'Rubidium', weight: '85.468', column: 1, row: 5, category: 'alkali metal' },
  { number: 38, symbol: 'Sr', name: 'Strontium', weight: '87.62', column: 2, row: 5, category: 'alkaline earth metal' },
  { number: 39, symbol: 'Y', name: 'Yttrium', weight: '88.906', column: 3, row: 5, category: 'transition metal' },
  { number: 40, symbol: 'Zr', name: 'Zirconium', weight: '91.224', column: 4, row: 5, category: 'transition metal' },
  { number: 41, symbol: 'Nb', name: 'Niobium', weight: '92.906', column: 5, row: 5, category: 'transition metal' },
  { number: 42, symbol: 'Mo', name: 'Molybdenum', weight: '95.95', column: 6, row: 5, category: 'transition metal' },
  { number: 43, symbol: 'Tc', name: 'Technetium', weight: '(98)', column: 7, row: 5, category: 'transition metal' },
  { number: 44, symbol: 'Ru', name: 'Ruthenium', weight: '101.07', column: 8, row: 5, category: 'transition metal' },
  { number: 45, symbol: 'Rh', name: 'Rhodium', weight: '102.91', column: 9, row: 5, category: 'transition metal' },
  { number: 46, symbol: 'Pd', name: 'Palladium', weight: '106.42', column: 10, row: 5, category: 'transition metal' },
  { number: 47, symbol: 'Ag', name: 'Silver', weight: '107.87', column: 11, row: 5, category: 'transition metal' },
  { number: 48, symbol: 'Cd', name: 'Cadmium', weight: '112.41', column: 12, row: 5, category: 'transition metal' },
  { number: 49, symbol: 'In', name: 'Indium', weight: '114.82', column: 13, row: 5, category: 'post-transition metal' },
  { number: 50, symbol: 'Sn', name: 'Tin', weight: '118.71', column: 14, row: 5, category: 'post-transition metal' },
  { number: 51, symbol: 'Sb', name: 'Antimony', weight: '121.76', column: 15, row: 5, category: 'metalloid' },
  { number: 52, symbol: 'Te', name: 'Tellurium', weight: '127.60', column: 16, row: 5, category: 'metalloid' },
  { number: 53, symbol: 'I', name: 'Iodine', weight: '126.90', column: 17, row: 5, category: 'halogen' },
  { number: 54, symbol: 'Xe', name: 'Xenon', weight: '131.29', column: 18, row: 5, category: 'noble gas' },
  { number: 55, symbol: 'Cs', name: 'Cesium', weight: '132.91', column: 1, row: 6, category: 'alkali metal' },
  { number: 56, symbol: 'Ba', name: 'Barium', weight: '137.33', column: 2, row: 6, category: 'alkaline earth metal' },
  { number: 57, symbol: 'La', name: 'Lanthanum', weight: '138.91', column: 3, row: 9, category: 'lanthanide' },
  { number: 72, symbol: 'Hf', name: 'Hafnium', weight: '178.49', column: 4, row: 6, category: 'transition metal' },
  { number: 73, symbol: 'Ta', name: 'Tantalum', weight: '180.95', column: 5, row: 6, category: 'transition metal' },
  { number: 74, symbol: 'W', name: 'Tungsten', weight: '183.84', column: 6, row: 6, category: 'transition metal' },
  { number: 75, symbol: 'Re', name: 'Rhenium', weight: '186.21', column: 7, row: 6, category: 'transition metal' },
  { number: 76, symbol: 'Os', name: 'Osmium', weight: '190.23', column: 8, row: 6, category: 'transition metal' },
  { number: 77, symbol: 'Ir', name: 'Iridium', weight: '192.22', column: 9, row: 6, category: 'transition metal' },
  { number: 78, symbol: 'Pt', name: 'Platinum', weight: '195.08', column: 10, row: 6, category: 'transition metal' },
  { number: 79, symbol: 'Au', name: 'Gold', weight: '196.97', column: 11, row: 6, category: 'transition metal' },
  { number: 80, symbol: 'Hg', name: 'Mercury', weight: '200.59', column: 12, row: 6, category: 'transition metal' },
  { number: 81, symbol: 'Tl', name: 'Thallium', weight: '204.38', column: 13, row: 6, category: 'post-transition metal' },
  { number: 82, symbol: 'Pb', name: 'Lead', weight: '207.2', column: 14, row: 6, category: 'post-transition metal' },
  { number: 83, symbol: 'Bi', name: 'Bismuth', weight: '208.98', column: 15, row: 6, category: 'post-transition metal' },
  { number: 84, symbol: 'Po', name: 'Polonium', weight: '(209)', column: 16, row: 6, category: 'metalloid' },
  { number: 85, symbol: 'At', name: 'Astatine', weight: '(210)', column: 17, row: 6, category: 'metalloid' },
  { number: 86, symbol: 'Rn', name: 'Radon', weight: '(222)', column: 18, row: 6, category: 'noble gas' },
  { number: 87, symbol: 'Fr', name: 'Francium', weight: '(223)', column: 1, row: 7, category: 'alkali metal' },
  { number: 88, symbol: 'Ra', name: 'Radium', weight: '(226)', column: 2, row: 7, category: 'alkaline earth metal' },
  { number: 89, symbol: 'Ac', name: 'Actinium', weight: '(227)', column: 3, row: 10, category: 'actinide' },
  { number: 104, symbol: 'Rf', name: 'Rutherfordium', weight: '(267)', column: 4, row: 7, category: 'transition metal' },
  { number: 105, symbol: 'Db', name: 'Dubnium', weight: '(270)', column: 5, row: 7, category: 'transition metal' },
  { number: 106, symbol: 'Sg', name: 'Seaborgium', weight: '(271)', column: 6, row: 7, category: 'transition metal' },
  { number: 107, symbol: 'Bh', name: 'Bohrium', weight: '(270)', column: 7, row: 7, category: 'transition metal' },
  { number: 108, symbol: 'Hs', name: 'Hassium', weight: '(277)', column: 8, row: 7, category: 'transition metal' },
  { number: 109, symbol: 'Mt', name: 'Meitnerium', weight: '(276)', column: 9, row: 7, category: 'transition metal' },
  { number: 110, symbol: 'Ds', name: 'Darmstadtium', weight: '(281)', column: 10, row: 7, category: 'transition metal' },
  { number: 111, symbol: 'Rg', name: 'Roentgenium', weight: '(282)', column: 11, row: 7, category: 'transition metal' },
  { number: 112, symbol: 'Cn', name: 'Copernicium', weight: '(285)', column: 12, row: 7, category: 'transition metal' },
  { number: 113, symbol: 'Nh', name: 'Nihonium', weight: '(286)', column: 13, row: 7, category: 'post-transition metal' },
  { number: 114, symbol: 'Fl', name: 'Flerovium', weight: '(289)', column: 14, row: 7, category: 'post-transition metal' },
  { number: 115, symbol: 'Mc', name: 'Moscovium', weight: '(290)', column: 15, row: 7, category: 'post-transition metal' },
  { number: 116, symbol: 'Lv', name: 'Livermorium', weight: '(293)', column: 16, row: 7, category: 'post-transition metal' },
  { number: 117, symbol: 'Ts', name: 'Tennessine', weight: '(294)', column: 17, row: 7, category: 'halogen' },
  { number: 118, symbol: 'Og', name: 'Oganesson', weight: '(294)', column: 18, row: 7, category: 'noble gas' },
  // Lanthanides
  { number: 58, symbol: 'Ce', name: 'Cerium', weight: '140.12', column: 4, row: 9, category: 'lanthanide' },
  { number: 59, symbol: 'Pr', name: 'Praseodymium', weight: '140.91', column: 5, row: 9, category: 'lanthanide' },
  { number: 60, symbol: 'Nd', name: 'Neodymium', weight: '144.24', column: 6, row: 9, category: 'lanthanide' },
  { number: 61, symbol: 'Pm', name: 'Promethium', weight: '(145)', column: 7, row: 9, category: 'lanthanide' },
  { number: 62, symbol: 'Sm', name: 'Samarium', weight: '150.36', column: 8, row: 9, category: 'lanthanide' },
  { number: 63, symbol: 'Eu', name: 'Europium', weight: '151.96', column: 9, row: 9, category: 'lanthanide' },
  { number: 64, symbol: 'Gd', name: 'Gadolinium', weight: '157.25', column: 10, row: 9, category: 'lanthanide' },
  { number: 65, symbol: 'Tb', name: 'Terbium', weight: '158.93', column: 11, row: 9, category: 'lanthanide' },
  { number: 66, symbol: 'Dy', name: 'Dysprosium', weight: '162.50', column: 12, row: 9, category: 'lanthanide' },
  { number: 67, symbol: 'Ho', name: 'Holmium', weight: '164.93', column: 13, row: 9, category: 'lanthanide' },
  { number: 68, symbol: 'Er', name: 'Erbium', weight: '167.26', column: 14, row: 9, category: 'lanthanide' },
  { number: 69, symbol: 'Tm', name: 'Thulium', weight: '168.93', column: 15, row: 9, category: 'lanthanide' },
  { number: 70, symbol: 'Yb', name: 'Ytterbium', weight: '173.04', column: 16, row: 9, category: 'lanthanide' },
  { number: 71, symbol: 'Lu', name: 'Lutetium', weight: '174.97', column: 17, row: 9, category: 'lanthanide' },
  // Actinides
  { number: 90, symbol: 'Th', name: 'Thorium', weight: '232.04', column: 4, row: 10, category: 'actinide' },
  { number: 91, symbol: 'Pa', name: 'Protactinium', weight: '231.04', column: 5, row: 10, category: 'actinide' },
  { number: 92, symbol: 'U', name: 'Uranium', weight: '238.03', column: 6, row: 10, category: 'actinide' },
  { number: 93, symbol: 'Np', name: 'Neptunium', weight: '(237)', column: 7, row: 10, category: 'actinide' },
  { number: 94, symbol: 'Pu', name: 'Plutonium', weight: '(244)', column: 8, row: 10, category: 'actinide' },
  { number: 95, symbol: 'Am', name: 'Americium', weight: '(243)', column: 9, row: 10, category: 'actinide' },
  { number: 96, symbol: 'Cm', name: 'Curium', weight: '(247)', column: 10, row: 10, category: 'actinide' },
  { number: 97, symbol: 'Bk', name: 'Berkelium', weight: '(247)', column: 11, row: 10, category: 'actinide' },
  { number: 98, symbol: 'Cf', name: 'Californium', weight: '(251)', column: 12, row: 10, category: 'actinide' },
  { number: 99, symbol: 'Es', name: 'Einsteinium', weight: '(252)', column: 13, row: 10, category: 'actinide' },
  { number: 100, symbol: 'Fm', name: 'Fermium', weight: '(257)', column: 14, row: 10, category: 'actinide' },
  { number: 101, symbol: 'Md', name: 'Mendelevium', weight: '(258)', column: 15, row: 10, category: 'actinide' },
  { number: 102, symbol: 'No', name: 'Nobelium', weight: '(259)', column: 16, row: 10, category: 'actinide' },
  { number: 103, symbol: 'Lr', name: 'Lawrencium', weight: '(262)', column: 17, row: 10, category: 'actinide' },
];


