export const ObjectTypeOptions = () => (
    <>
      <option value="Report">Report</option>
      <option value="Request for Synthesis">Request for Synthesis</option>
      <option value="Sample">Sample</option>
      <option value="SC-XRD Measurement (cif)">SC-XRD Measurement (cif)</option>
      <option value="SDC Processed (csv)">SDC Processed (csv)</option>
      <option value="SDC Raw (zip) DUE">SDC Raw (zip) DUE</option>
      <option value="SDC Raw (zip) RUB">SDC Raw (zip) RUB</option>
      <option value="SECCM (csv)">SECCM (csv)</option>
      <option value="SECCM Long-range Processed (csv)">SECCM Long-range Processed (csv)</option>
      <option value="SECCM Long-range Raw (zip)">SECCM Long-range Raw (zip)</option>
      <option value="SECCM/EBSD correlation (xlsx)">SECCM/EBSD correlation (xlsx)</option>
      <option value="SEM (image)">SEM (image)</option>
      <option value="Simulation Database">Simulation Database</option>
      <option value="Size distribution">Size distribution</option>
      <option value="Sputter Chamber">Sputter Chamber</option>
      <option value="Sputter Rate">Sputter Rate</option>
      <option value="Stress Measurement (DHM)">Stress Measurement (DHM)</option>
      <option value="Substrate">Substrate</option>
      <option value="Synchrotron">Synchrotron</option>
      <option value="Synthesis">Synthesis</option>
      <option value="Literature Reference">Literature Reference</option>
      <option value="LSV (xlsx, csv, txt)">LSV (xlsx, csv, txt)</option>
      <option value="Magnetic properties">Magnetic properties</option>
      <option value="Nanoindentation">Nanoindentation</option>
      <option value="NMR Measurement (zip)">NMR Measurement (zip)</option>
      <option value="Open Circuit Potential (csv, txt, dat)">Open Circuit Potential (csv, txt, dat)</option>
      <option value="Oscilloscope">Oscilloscope</option>
      <option value="PEIS (xlsx, csv, txt)">PEIS (xlsx, csv, txt)</option>
      <option value="Photo">Photo</option>
      <option value="Polymer">Polymer</option>
      <option value="PowerPoint Presentation Slides (ppt, pptx)">PowerPoint Presentation Slides (ppt, pptx)</option>
      <option value="Property Distribution (csv)">Property Distribution (csv)</option>
      <option value="Property Distribution Plot (Image)">Property Distribution Plot (Image)</option>
      <option value="Publication">Publication</option>
      <option value="Python Script (py, zip)">Python Script (py, zip)</option>
      <option value="Raman (txt)">Raman (txt)</option>
      <option value="Raw Document">Raw Document</option>
      <option value="APT">APT</option>
      <option value="Bandgap">Bandgap</option>
      <option value="Bandgap Reference Spectra (csv)">Bandgap Reference Spectra (csv)</option>
      <option value="Bandgap Sample Spectra (csv)">Bandgap Sample Spectra (csv)</option>
      <option value="Bandgap Tauc Plots (csv)">Bandgap Tauc Plots (csv)</option>
      <option value="Calculation/Computational Composition">Calculation/Computational Composition</option>
      <option value="Calculation/Computational Sample">Calculation/Computational Sample</option>
      <option value="Composition">Composition</option>
      <option value="Composition Test">Composition Test</option>
      <option value="Computational Composition Atom">Computational Composition Atom</option>
      <option value="CV Measurement (nox)">CV Measurement (nox)</option>
      <option value="CV Measurement (xlsx, csv, txt)">CV Measurement (xlsx, csv, txt)</option>
      <option value="DACA Image (jpg)">DACA Image (jpg)</option>
      <option value="DACA Raw (csv)">DACA Raw (csv)</option>
      <option value="DACV Image (jpg)">DACV Image (jpg)</option>
      <option value="DACV Raw (csv)">DACV Raw (csv)</option>
      <option value="DCA Log File">DCA Log File</option>
      <option value="DSC Measurement (txt)">DSC Measurement (txt)</option>
      <option value="EDX CSV">EDX CSV</option>
      <option value="EDX Image">EDX Image</option>
      <option value="EDX Raw (ip)">EDX Raw (ip)</option>
      <option value="EDX Raw (txt)">EDX Raw (txt)</option>
      <option value="EDX Raw Other">EDX Raw Other</option>
      <option value="Electrocatalytic activity">Electrocatalytic activity</option>
      <option value="Electrochemical data (csv, txt)">Electrochemical data (csv, txt)</option>
      <option value="Handover">Handover</option>
      <option value="Hardness modulus">Hardness modulus</option>
      <option value="HTTS Resistance CSV">HTTS Resistance CSV</option>
      <option value="HTTS Resistance Image">HTTS Resistance Image</option>
      <option value="HTTS Resistance TXT">HTTS Resistance TXT</option>
      <option value="Hypothesis">Hypothesis</option>
      <option value="Ideas or experiment plans">Ideas or experiment plans</option>
      <option value="Insitu IR Measurement (CIR)">Insitu IR Measurement (CIR)</option>
      <option value="IR Measurement (dpt)">IR Measurement (dpt)</option>
      <option value="Link Type">Link Type</option>
    </>
);
